[package]
name = "hikvision-sadp-client"
version = "0.1.0"
authors = ["cub3d"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.117", features = ["derive"] }
serde-xml-rs = "0.4.0"
uuid = { version = "0.8.1", features = ["v4"] }